version: 2.1
executors:
    # my-executorを定義
    my-executor:
        docker:
          - image: cimg/ruby:2.7.1-node
jobs:
  build:
      # my-executorを利用
    executor: my-executer
    steps:
      - run: echo Hello World